version: '3'
  web:
    build: .
    args:
      PARLIAMENT_BASE_URL: http://localhost:3030
      GTM_KEY: GTM-NNXTVV8
      ASSET_LOCATION_URL: https://s3-eu-west-1.amazonaws.com/web1devci.pugin-website
    ports:
      - "3000"
  api:
    build: ../member-service-api
    args:
      UKPDS_DATA_URI_PREFIX: http://id.ukpds.org
      UKPDS_DATA_ENDPOINT: http://51.140.42.21/repositories/Master
    ports:
      - "3030"
